CREATE TABLE public."DeckAccolades"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "DeckId" integer NOT NULL,
    "AccoladeId" text COLLATE pg_catalog."default" NOT NULL,
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "ImageUrl" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_DeckAccolades" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DeckAccolades_Decks" FOREIGN KEY ("DeckId")
        REFERENCES public."Decks" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)
TABLESPACE pg_default;

ALTER TABLE public."DeckAccolades"
    OWNER to keyteki;

CREATE INDEX "IX_DeckAccolades_DeckId"
    ON public."DeckAccolades" USING btree
    ("DeckId" ASC NULLS LAST)
    TABLESPACE pg_default;

ALTER TABLE "Users" ADD COLUMN "Settings_ShowAccolades" boolean DEFAULT true;
