-- Table: public."Expansions"

-- DROP TABLE public."Expansions";

CREATE TABLE public."Expansions"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ExpansionId" integer NOT NULL,
    "Code" text COLLATE pg_catalog."default",
    "Name" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Expansions" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."Expansions"
    OWNER to keyteki;