-- Table: public."Houses"

-- DROP TABLE public."Houses";

CREATE TABLE public."Houses"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Code" text COLLATE pg_catalog."default",
    "Name" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Houses" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."Houses"
    OWNER to keyteki;