-- Table: public."Cards"

-- DROP TABLE public."Cards";

CREATE TABLE public."Cards"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "CardId" text COLLATE pg_catalog."default",
    "Name" text COLLATE pg_catalog."default",
    "Number" text COLLATE pg_catalog."default",
    "Image" text COLLATE pg_catalog."default",
    "ExpansionId" integer NOT NULL,
    "Keywords" text COLLATE pg_catalog."default",
    "Traits" text COLLATE pg_catalog."default",
    "Type" text COLLATE pg_catalog."default",
    "Rarity" text COLLATE pg_catalog."default",
    "Amber" integer,
    "Armor" integer,
    "Power" integer,
    "Text" text COLLATE pg_catalog."default",
    "HouseId" integer NOT NULL,
    CONSTRAINT "PK_Cards" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Cards_Expansions_ExpansionId" FOREIGN KEY ("ExpansionId")
        REFERENCES public."Expansions" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_Cards_Houses_HouseId" FOREIGN KEY ("HouseId")
        REFERENCES public."Houses" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public."Cards"
    OWNER to keyteki;
-- Index: IX_Cards_CardId_ExpansionId

-- DROP INDEX public."IX_Cards_CardId_ExpansionId";

CREATE UNIQUE INDEX "IX_Cards_CardId_ExpansionId"
    ON public."Cards" USING btree
    ("CardId" COLLATE pg_catalog."default" ASC NULLS LAST, "ExpansionId" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_Cards_ExpansionId

-- DROP INDEX public."IX_Cards_ExpansionId";

CREATE INDEX "IX_Cards_ExpansionId"
    ON public."Cards" USING btree
    ("ExpansionId" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_Cards_HouseId

-- DROP INDEX public."IX_Cards_HouseId";

CREATE INDEX "IX_Cards_HouseId"
    ON public."Cards" USING btree
    ("HouseId" ASC NULLS LAST)
    TABLESPACE pg_default;