-- Table: public."CardLocaleNames"

-- DROP TABLE public."CardLocaleNames";

CREATE TABLE public."CardLocaleNames"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "CardId" integer NOT NULL,
    "Locale" text COLLATE pg_catalog."default",
    "Name" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_CardLocaleNames" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CardLocaleNames_Cards_CardId" FOREIGN KEY ("CardId")
        REFERENCES public."Cards" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public."CardLocaleNames"
    OWNER to keyteki;
-- Index: IX_CardLocaleNames_CardId

-- DROP INDEX public."IX_CardLocaleNames_CardId";

CREATE INDEX "IX_CardLocaleNames_CardId"
    ON public."CardLocaleNames" USING btree
    ("CardId" ASC NULLS LAST)
    TABLESPACE pg_default;