-- Table: public."BlockList"

-- DROP TABLE public."BlockList";

CREATE TABLE public."BlockList"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer NOT NULL,
    "Entry" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_BlockList" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BlockList_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public."BlockList"
    OWNER to keyteki;
-- Index: IX_BlockList_UserId_Entry

-- DROP INDEX public."IX_BlockList_UserId_Entry";

CREATE INDEX "IX_BlockList_UserId_Entry"
    ON public."BlockList" USING btree
    ("UserId" ASC NULLS LAST, "Entry" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;