-- Table: public."BanList"

-- DROP TABLE public."BanList";

CREATE TABLE public."BanList"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Ip" text COLLATE pg_catalog."default",
    "CreatorId" integer NOT NULL,
    "Added" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_BanList" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BanList_Users_CreatorId" FOREIGN KEY ("CreatorId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public."BanList"
    OWNER to keyteki;
-- Index: IX_BanList_CreatorId

-- DROP INDEX public."IX_BanList_CreatorId";

CREATE INDEX "IX_BanList_CreatorId"
    ON public."BanList" USING btree
    ("CreatorId" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_BanList_Ip

-- DROP INDEX public."IX_BanList_Ip";

CREATE UNIQUE INDEX "IX_BanList_Ip"
    ON public."BanList" USING btree
    ("Ip" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;