-- Table: public."Games"

-- DROP TABLE public."Games";

CREATE TABLE public."Games"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "GameId" text COLLATE pg_catalog."default",
    "GameType" text COLLATE pg_catalog."default",
    "GameFormat" text COLLATE pg_catalog."default",
    "StartedAt" timestamp without time zone,
    "FinishedAt" timestamp without time zone,
    "WinReason" text COLLATE pg_catalog."default",
    "WinnerId" integer,
    CONSTRAINT "PK_Games" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Games_Users_WinnerId" FOREIGN KEY ("WinnerId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
)

TABLESPACE pg_default;

ALTER TABLE public."Games"
    OWNER to keyteki;
-- Index: IX_Games_GameId

-- DROP INDEX public."IX_Games_GameId";

CREATE UNIQUE INDEX "IX_Games_GameId"
    ON public."Games" USING btree
    ("GameId" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_Games_WinnerId

-- DROP INDEX public."IX_Games_WinnerId";

CREATE INDEX "IX_Games_WinnerId"
    ON public."Games" USING btree
    ("WinnerId" ASC NULLS LAST)
    TABLESPACE pg_default;