-- Table: public."Messages"

-- DROP TABLE public."Messages";

CREATE TABLE public."Messages"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "PosterId" integer NOT NULL,
    "Text" text COLLATE pg_catalog."default",
    "PostedTime" timestamp without time zone NOT NULL,
    "Deleted" timestamp without time zone,
    "DeletedById" integer,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Messages_Users_DeletedById" FOREIGN KEY ("DeletedById")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT "FK_Messages_Users_PosterId" FOREIGN KEY ("PosterId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public."Messages"
    OWNER to keyteki;
-- Index: IX_Messages_DeletedById

-- DROP INDEX public."IX_Messages_DeletedById";

CREATE INDEX "IX_Messages_DeletedById"
    ON public."Messages" USING btree
    ("DeletedById" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_Messages_PosterId

-- DROP INDEX public."IX_Messages_PosterId";

CREATE INDEX "IX_Messages_PosterId"
    ON public."Messages" USING btree
    ("PosterId" ASC NULLS LAST)
    TABLESPACE pg_default;