-- Table: public."News"

-- DROP TABLE public."News";

CREATE TABLE public."News"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Text" text COLLATE pg_catalog."default",
    "PosterId" integer NOT NULL,
    "PostedDate" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_News" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_News_Users_PosterId" FOREIGN KEY ("PosterId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public."News"
    OWNER to keyteki;
-- Index: IX_News_PosterId

-- DROP INDEX public."IX_News_PosterId";

CREATE INDEX "IX_News_PosterId"
    ON public."News" USING btree
    ("PosterId" ASC NULLS LAST)
    TABLESPACE pg_default;