-- Table: public."Tags"

-- DROP TABLE public."Tags";

CREATE TABLE public."Tags"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer NOT NULL,
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Color" text COLLATE pg_catalog."default" DEFAULT '#007bff',
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_Tags" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tags_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "UK_Tags_UserId_Name" UNIQUE ("UserId", "Name")
)

TABLESPACE pg_default;

ALTER TABLE public."Tags"
    OWNER to keyteki;

-- Index: IX_Tags_UserId

-- DROP INDEX public."IX_Tags_UserId";

CREATE INDEX "IX_Tags_UserId"
    ON public."Tags" USING btree
    ("UserId" ASC NULLS LAST)
    TABLESPACE pg_default;

-- Note: Tag limit per user (10) is enforced in the application logic via TagService
