-- Table: public."DeckTags"

-- DROP TABLE public."DeckTags";

CREATE TABLE public."DeckTags"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "DeckId" integer NOT NULL,
    "TagId" integer NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_DeckTags" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DeckTags_Decks_DeckId" FOREIGN KEY ("DeckId")
        REFERENCES public."Decks" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_DeckTags_Tags_TagId" FOREIGN KEY ("TagId")
        REFERENCES public."Tags" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "UK_DeckTags_DeckId_TagId" UNIQUE ("DeckId", "TagId")
)

TABLESPACE pg_default;

ALTER TABLE public."DeckTags"
    OWNER to keyteki;

-- Index: IX_DeckTags_DeckId

-- DROP INDEX public."IX_DeckTags_DeckId";

CREATE INDEX "IX_DeckTags_DeckId"
    ON public."DeckTags" USING btree
    ("DeckId" ASC NULLS LAST)
    TABLESPACE pg_default;

-- Index: IX_DeckTags_TagId

-- DROP INDEX public."IX_DeckTags_TagId";

CREATE INDEX "IX_DeckTags_TagId"
    ON public."DeckTags" USING btree
    ("TagId" ASC NULLS LAST)
    TABLESPACE pg_default;

-- Note: Tag limit per deck (10) is enforced in the application logic via TagService
