apiVersion: v1
kind: ConfigMap
metadata:
    name: keyteki-static-nginx-config
    # prettier-ignore
    namespace: {{ .Values.namespace }}
data:
    nginx.conf: |
        worker_processes auto;
        error_log /dev/stderr warn;
        pid /var/run/nginx.pid;

        events {
            worker_connections 1024;
        }

        http {
            include /etc/nginx/mime.types;
            default_type application/octet-stream;

            log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                            '$status $body_bytes_sent "$http_referer" '
                            '"$http_user_agent" "$http_x_forwarded_for"';

            access_log /dev/stdout main;

            sendfile on;
            tcp_nopush on;
            tcp_nodelay on;
            keepalive_timeout 65;
            types_hash_max_size 2048;

            # Enable gzip compression
            gzip on;
            gzip_vary on;
            gzip_proxied any;
            gzip_comp_level 6;
            gzip_types text/plain text/css text/xml text/javascript application/json application/javascript application/xml+rss image/svg+xml;

            server {
                listen 80;
                server_name _;

                root /usr/share/nginx/html;

                # Card images - cache for 7 days (immutable)
                location /img/cards/ {
                    expires 7d;
                    add_header Cache-Control "public, immutable";
                    access_log off;
                }

                # Avatars - cache for 1 day (users can update)
                location /img/avatar/ {
                    expires 1d;
                    add_header Cache-Control "public";
                    access_log off;
                }

                # Health check endpoint
                location /health {
                    access_log off;
                    return 200 "OK\n";
                    add_header Content-Type text/plain;
                }
            }
        }
